# Generated by Django 3.2.9 on 2021-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
