# Generated by Django 3.2.9 on 2021-11-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='task_status',
            field=models.BooleanField(default=True),
        ),
    ]
